### ISSUE TITLE
`engagement_tasks` model trying to pull missing column `probability_to_complete`.

### ISSUE THREAD

**Issue by fadhguru** [fivetran/dbt_hubspot#31] opened 2021-02-28 15:17 UTC
Thank you for the great work done on this package. There appears to be a schema-mismatch issue that's preventing this package to be usable right now. 

I can confirm that the `probability_to_complete` is not present in the current schema for the `engagement_tasks` table. The fivetran connection was created a week ago with no all schemas enabled.

The problem also is simply having `hubspot_engagement_tasks_enabled: false` doesn't fix it at all, the model still gets materialized. The only way I was able to get it to work was setting `hubspot_sales_enabled: false`.

See the generated SQL below for the `stg_hubspot__engagement_task` model:

```sql
with base as (

    select *
    from `PROJECT`.`DATASET`.`engagement_task`

), fields as (

    select
        _fivetran_synced,
        body as task_note,
        completion_date as completion_timestamp,
        engagement_id,
        for_object_type,
        is_all_day,
        priority,
        probability_to_complete,
        status as task_status,
        subject as task_subject,
        task_type
    from base
    
)

select *
from fields;
```

**Comment by fivetran-joemarkiewicz** [comment] 2021-03-22 15:27
Hi @fadhguru thank you for opening this issue. From the generated SQL you provided, it seems you are using our v0.1.0 release of the HubSpot dbt package. the v0.2.0 release of this package will fix the issue you are seeing with the `probability_to_complete`.

Please use the below snippet to update your dependency within your `packages.yml` file:
```
packages:
  - package: fivetran/hubspot
    version: 0.2.0
```

After updating your `packages.yml` file, I would run `dbt clean && dbt deps` prior to running your models. Please let us know if the issue still persists after applying the proposed changes to your dbt project.

**Comment by fivetran-joemarkiewicz** [comment] 2021-04-06 15:33
Hi @fadhguru with the release of v0.2.0 the issue you originally opened should be fixed. I will close this ticket as I assumed the issue is not persisting on your end.

If the issue is still present for you, I ask you open another issue and we can continue from there. Thank you!

**Closed by fivetran-joemarkiewicz** 2021-04-06 15:33 UTC
